### ISSUE TITLE
Specular peak location wrong when using flat detector

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#918] opened 2020-04-03 18:47 UTC
When including the specular peak in a GISAS simulation with a flat detector that is positioned manually the location of the peak is not as expected. The GISAS scattering works without issues.

### Expected behavior
Specular is at alpha_f=alpha_i.

### Actual behavior
Only true for angular based detector definition, flat detector shows spot at location not expected by the angle.

### Steps to reproduce the behavior
Minimal examples of working angular detector and flat detector is attached.
[issue_flat_sim.zip](https://github.com/scgmlz/BornAgain/files/4429327/issue_flat_sim.zip)

### Platforms affected
Any.

**Comment by jwuttke** [comment] 2020-09-16 12:00
The nontrivial computation is in RectangularDetector::indexOfSpecular.

**Comment by jwuttke** [comment] 2020-09-17 05:02
The cause of the bug is `m_distance=0`.

**Comment by jwuttke** [comment] 2020-09-17 07:40
Resolved in commit [424d02](https://github.com/scgmlz/BornAgain/pull/1048/commits/424d026e9ccc12d15eec0f648494115c1eb19adb), PR [1048](https://github.com/scgmlz/BornAgain/pull/1048)

**Closed by jwuttke** 2020-09-17 07:40 UTC
Labels: bug:incorrect
