### ISSUE TITLE
ModuleNotFoundError: No module named 'bornagain._libBornAgainFit'

### ISSUE THREAD

**Issue by Li-MingWang** [scgmlz/BornAgain#967] opened 2020-06-14 04:07 UTC

**Comment by mganeva** [comment] 2020-06-15 15:17
Hi Li-Ming,
to help you we need more information:
- which operating system do you use?
- which version of Python do you use?
- what do you do to get this error message?

If you have Windows, did you check our [installation instructions](https://www.bornagainproject.org/documentation/getting-started/installation/windows/) and [trouleshooting](https://www.bornagainproject.org/documentation/getting-started/installation/windows/python-troubleshooting/) documentation pages?

**Comment by Li-MingWang** [comment] 2020-06-16 00:51
> Hi Li-Ming,
> to help you we need more information:
> 
> * which operating system do you use?
> * which version of Python do you use?
> * what do you do to get this error message?
> 
> If you have Windows, did you check our [installation instructions](https://www.bornagainproject.org/documentation/getting-started/installation/windows/) and [trouleshooting](https://www.bornagainproject.org/documentation/getting-started/installation/windows/python-troubleshooting/) documentation pages?

Hi mganeva，
I install the Bornagain 1.16 first and then python 3.8. I just export the python script from the simulation step, and run the script under python IDLE. the error occurs. does the order of the installation of Bornagain and python matters?

**Comment by Li-MingWang** [comment] 2020-06-16 09:06
Hi mganeva，
Now it works. it seems Bornagain 1.16 is not compatible  with the latest version python 3.8, but it works with python 3.7.

**Comment by mganeva** [comment] 2020-06-16 09:54
Hi @Li-MingWang, great!
BornAgain 1.16 has been released before Python 3.8 and has not been tested with it. 
Very soon we plan to release BornAgain 1.17 which will work also with Python 3.8.

**Comment by mganeva** [comment] 2020-06-16 09:55
Since the problem is solved, I close this issue.

**Closed by mganeva** 2020-06-16 09:55 UTC
